version: '3'

services:
  go-server:
    image: etodd/playtest-telemetry-server:latest
    expose:
      - "8000"
    restart: unless-stopped
    environment:
      PLAYTEST_DATA_DIR: /data
      PLAYTEST_USERNAME: ${PLAYTEST_USERNAME:-}
      PLAYTEST_PASSWORD: ${PLAYTEST_PASSWORD:-}
      PLAYTEST_API_KEY: ${PLAYTEST_API_KEY:-}
    volumes:
      - data:/data

  caddy:
    image: caddy:2.6-alpine
    ports:
      - 80:80
      - 443:443
    depends_on:
      - go-server
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    command: caddy reverse-proxy --from ${PLAYTEST_DOMAIN} --to go-server:8000

volumes:
  data:
  caddy_data:
  caddy_config: